name: Hello

on:
  workflow_dispatch:

jobs:
  greet-the-servers:
    name: Greet the servers
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ["app-server-1", "app-server-2", "db-server"]
    steps:
      - name: Echo Git commit hash
        run: |
          echo "Git commit hash: ${{ github.sha }}"
      - name: Echo workflow run number
        run: |
          echo "Github Actions run number: ${{ github.run_number }}"
      - name: Greet a server
        run: |
          echo "Hello server ${{ matrix.server }}"
